//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidato()
        {
            this.votos = new HashSet<votos>();
        }
    
        public int codigo_candidato { get; set; }
        public string nome_candidato { get; set; }
        public string numeroeleitoral_candidato { get; set; }
        public Nullable<int> codigo_partido { get; set; }
        public Nullable<int> codigo_cargo { get; set; }
    
        public virtual partido partido { get; set; }
        public virtual cargo cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<votos> votos { get; set; }
    }
}
