//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class eleitor
    {
        public int codigo_eleitor { get; set; }
        public string nome_eleitor { get; set; }
        public string titulo_eleitor { get; set; }
        public Nullable<System.DateTime> datanascimento_eleitor { get; set; }
        public Nullable<int> codigo_secao { get; set; }
        public Nullable<int> presenca_eleitor { get; set; }
    
        public virtual secao secao { get; set; }
    }
}
