//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eleicoesEntities : DbContext
    {
        public eleicoesEntities()
            : base("name=eleicoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidato> candidato { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<eleitor> eleitor { get; set; }
        public virtual DbSet<partido> partido { get; set; }
        public virtual DbSet<secao> secao { get; set; }
        public virtual DbSet<urna> urna { get; set; }
        public virtual DbSet<votos> votos { get; set; }
        public virtual DbSet<zona> zona { get; set; }
        public virtual DbSet<vw_candidatos> vw_candidatos { get; set; }
    }
}
