//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class urna
    {
        public int codigo_urna { get; set; }
        public string identificador_urna { get; set; }
        public Nullable<System.DateTime> dataabertura_urna { get; set; }
        public Nullable<System.DateTime> datafechamento_urna { get; set; }
        public Nullable<System.TimeSpan> horaabertura_urna { get; set; }
        public Nullable<System.TimeSpan> horafechamento_urna { get; set; }
        public Nullable<int> codigo_secao { get; set; }
    
        public virtual secao secao { get; set; }
    }
}
