//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class voto
    {
        public int codigo_voto { get; set; }
        public Nullable<System.DateTime> data_voto { get; set; }
        public Nullable<int> codigo_candidato { get; set; }
    
        public virtual candidato candidato { get; set; }
    }
}
