//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_candidatos
    {
        public int codigo_candidato { get; set; }
        public string nome_candidato { get; set; }
        public Nullable<int> numeroeleitoral_candidato { get; set; }
        public string nome_cargo { get; set; }
        public string nome_partido { get; set; }
        public string sigla_partido { get; set; }
    }
}
